### ISSUE TITLE
optimal objective function value

### ISSUE THREAD

**Issue by EnzoIsrael** [cureos/jcobyla#2]
sorry if it's silly, but the output "F" is the optimal value of the objective function?

**Comment by anders9ustafsson** [comment]
Not silly at all :-)

To explicitly obtain the optimal function value you need to call the `Compute` method in the `Calcfc` interface implementation that you passed into `Cobyla.FindMinimum`. You need to call `Compute` with the `x` values that has been output from the optimization. Remember to also send in a `con` array of at least length `m`.

**Comment by EnzoIsrael** [comment]
ok I will. I am implementing this library in a research university. Thank you.
