### ISSUE TITLE
numerical stability?

### ISSUE THREAD

**Issue by jovrstra** [cureos/jcobyla#3]
Hello,
I'm using jcobyla for a minimization problem, but when testing some things some results are showing unexpected jumps. 

Iterating over my goals, I see that the solutions of jcobyla generally presents curves that should be smooth, but there are some big unexpected jumps at some places. The iteration finished normally, so it is not that there were not enough iterations. I've tried increasing the rho-end, as well as my epsilon test (conditions is for equality to zero) but it does not solve the issue. Surprisingly, there seem to be less such jumps with a lower rho-end.

Could I be running in to issues due to double representation? Or is there something in the iterative algorithm that may explain it?

Thanks

**Comment by jovrstra** [comment]
Shifting the functions along the x-axis, away from zero seems to solve my problem (I can do this without it affecting the goal).

**Comment by anders9ustafsson** [comment]
Hi @jovrstra and sorry for not having responded earlier. I have to admit that I am no expert in the algorithmic intricacies of the COBYLA algorithm; I have primarily focused on migrating the COBYLA algorithm from the C implementation to C# and Java. If you need guidance on how to workaround issues like the jumps, it is probably a better idea to ask the question on a general numerical optimization forum.

**Comment by jovrstra** [comment]
Thank you for the reply. 
I'm also not an expert in numerical algorithms... :) I suspect the jumps are caused by the limited representation of doubles in Java. The fact that it jumps much less when I shift my entire "problem" along the x-axis so I don't have values on X that are close to 0 seems to support that idea (theoretically, a shift of the entire problem should just give a similar shift of the solution). I've tried replacing all doubles in the algorithm with bigdecimals, but then it is unworkably slow. For me, shifting the problem makes it workable enough for my purpose. :)
