### ISSUE TITLE
citation data for JCobyla in scientific article?

### ISSUE THREAD

**Issue by jovrstra** [cureos/jcobyla#4]
Hello,
Is there a preferred way of citing this jcobyla implementation in publications, or is the github data sufficient? 
I'm using it as part of a solution and will cite it in the references; some algorithms/implementations provide some citation data so I prefer to ask.
Thanks,
Jörg

**Comment by anders9ustafsson** [comment]
Hi Jörg, 

I haven't thought much about it, but you could cite Powell's article on the COBYLA2 algorithm (see the README page or [here](https://scholar.google.com/citations?user=p3kDmy0AAAAJ#d=gs_md_cita-d&u=%2Fcitations%3Fview_op%3Dview_citation%26hl%3Den%26user%3Dp3kDmy0AAAAJ%26citation_for_view%3Dp3kDmy0AAAAJ%3AdhFuZR0502QC%26tzom%3D-120)), or you could use the form suggested in [this](https://www.software.ac.uk/how-cite-software) article to cite JCOBYLA directly. Either way is fine with me.
